version: '2.1'

services:
  get-http-page-title:
    image: get-http-page-title
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 6643:6643
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js